
server:
  port: 8080  #tomcat端口

spring: #springboot的配置
  thymeleaf:
    prefix: classpath:/static/
  mvc:
    static-path-pattern: /**
  datasource: #定义数据源
    name: test
    #127.0.0.1为本机测试的ip，3306是mysql的端口号。serverTimezone是定义时区，照抄就好，mysql高版本需要定义这些东西
    #useSSL也是某些高版本mysql需要问有没有用SSL连接
    url: jdbc:mysql://localhost:3306/ebook?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root  #数据库用户名，root为管理员
    password: 123456 #该数据库用户的密码
  resources:
    static-locations: classpath:static

mybatis:  #mybatyis的配置
  mapper-locations: classpath:mapper/*.xml #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
  type-aliases-package: com.example.springboot_ebook.model #起别名。可省略写mybatis的xml中的resultType的全路径






